export const packages = [
  '@commitlint/cli',
  '@commitlint/config-conventional',
  '@cspell/eslint-plugin',
  '@eslint/config-helpers',
  '@eslint/eslintrc',
  '@next/eslint-plugin-next',
  '@typescript-eslint/eslint-plugin',
  '@typescript-eslint/eslint-plugin-tslint',
  '@typescript-eslint/parser',
  'commitizen',
  'cspell',
  'prettier',
  'cz-conventional-changelog',
  'eslint',
  'eslint-config-prettier',
  'eslint-import-resolver-typescript',
  'eslint-plugin-import',
  'eslint-plugin-prettier',
  'eslint-plugin-react-hooks',
  'eslint-plugin-unicorn',
  'husky',
  'lint-staged',
] as const;
